# Generated by Django 5.2.2 on 2025-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_location_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('broken', 'Broken'), ('missing', 'Missing')], default='available', max_length=20),
        ),
    ]
