# Generated by Django 5.2.2 on 2025-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dimension',
            field=models.CharField(default=1900, max_length=50),
            preserve_default=False,
        ),
    ]
