# Generated by Django 5.2.2 on 2025-06-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
