# Generated by Django 5.2.2 on 2025-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0002_borrowrequest_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('broken', 'Broken'), ('missing', 'Missing')], default='good', max_length=20),
        ),
    ]
