# Generated by Django 5.2.2 on 2025-06-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0003_alter_borrowrequest_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
