# Generated by Django 5.2.2 on 2025-06-27 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0004_returnrequest_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
