# Generated by Django 5.2.2 on 2025-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0005_alter_borrowrequest_date_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='review',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='review',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
