# Generated by Django 5.2.2 on 2025-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0006_remove_borrowrequest_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
