# Generated by Django 5.2.2 on 2025-07-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0007_borrowrequest_date_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
