# Generated by Django 5.2.2 on 2025-07-30 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_requests', '0008_borrowrequest_seen_returnrequest_seen'),
        ('devices', '0006_device_dimension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedBorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('date_requested', models.DateField()),
                ('return_date', models.DateField()),
                ('review', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_borrow_requests', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_borrow_requests', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('date_returned', models.DateTimeField()),
                ('condition', models.CharField(choices=[('good', 'Good'), ('broken', 'Broken'), ('missing', 'Missing')], max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('review', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_return_requests', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_return_requests', to='devices.device')),
            ],
        ),
    ]
