# Generated by Django 5.2.2 on 2025-07-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
